# 配置无数据源启动
#spring:
#  datasource:
#    dynamic:
#      primary: master #设置默认的数据源或者数据源组,默认值即为master
#      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.

# JPA 启动必须设置一个数据源
spring:
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/test_0?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&useSSL=false
          username: root
          password: 123456
  profiles:
    active: local
logging:
  level:
    root: info